@gen function ppmodel()
    # source: https://github.com/StatisticalRethinkingJulia/MCMCBenchmarkSuite.jl/tree/master
    
    # Original
    # mu ~ normal(0, 1)
    # sigma ~ cauchy(0,5)
    # y ~ normal(mu,sigma)

    # Modified since Cauchy distribution is not yet supported 
    mu ~ normal(100, 30)
    sigma ~ uniform(1,50) # TODO redo to something more similar to cauchy 
    
    y1 ~ normal(mu, sigma)
    y2 ~ normal(mu, sigma)
    y3 ~ normal(mu, sigma)
    y4 ~ normal(mu, sigma)
    y5 ~ normal(mu, sigma)
    y6 ~ normal(mu, sigma)
    y7 ~ normal(mu, sigma)
    y8 ~ normal(mu, sigma)
    y9 ~ normal(mu, sigma)
    y10 ~ normal(mu, sigma)
    y11 ~ normal(mu, sigma)
    y12 ~ normal(mu, sigma)
    y13 ~ normal(mu, sigma)
    y14 ~ normal(mu, sigma)
    y15 ~ normal(mu, sigma)
    y16 ~ normal(mu, sigma)
    y17 ~ normal(mu, sigma)
    y18 ~ normal(mu, sigma)
    y19 ~ normal(mu, sigma)
    y20 ~ normal(mu, sigma)
    # y21 ~ normal(mu, sigma)
    # y22 ~ normal(mu, sigma)
    # y23 ~ normal(mu, sigma)
    # y24 ~ normal(mu, sigma)
    # y25 ~ normal(mu, sigma)
    # y26 ~ normal(mu, sigma)
    # y27 ~ normal(mu, sigma)
    # y28 ~ normal(mu, sigma)
    # y29 ~ normal(mu, sigma)
    # y30 ~ normal(mu, sigma)
    # y31 ~ normal(mu, sigma)
    # y32 ~ normal(mu, sigma)
    # y33 ~ normal(mu, sigma)
    # y34 ~ normal(mu, sigma)
    # y35 ~ normal(mu, sigma)
    # y36 ~ normal(mu, sigma)
    # y37 ~ normal(mu, sigma)
    # y38 ~ normal(mu, sigma)
    # y39 ~ normal(mu, sigma)
    # y40 ~ normal(mu, sigma)
    # y41 ~ normal(mu, sigma)
    # y42 ~ normal(mu, sigma)
    # y43 ~ normal(mu, sigma)
    # y44 ~ normal(mu, sigma)
    # y45 ~ normal(mu, sigma)
    # y46 ~ normal(mu, sigma)
    # y47 ~ normal(mu, sigma)
    # y48 ~ normal(mu, sigma)
    # y49 ~ normal(mu, sigma)
    # y50 ~ normal(mu, sigma)
    # y51 ~ normal(mu, sigma)
    # y52 ~ normal(mu, sigma)
    # y53 ~ normal(mu, sigma)
    # y54 ~ normal(mu, sigma)
    # y55 ~ normal(mu, sigma)
    # y56 ~ normal(mu, sigma)
    # y57 ~ normal(mu, sigma)
    # y58 ~ normal(mu, sigma)
    # y59 ~ normal(mu, sigma)
    # y60 ~ normal(mu, sigma)
    # y61 ~ normal(mu, sigma)
    # y62 ~ normal(mu, sigma)
    # y63 ~ normal(mu, sigma)
    # y64 ~ normal(mu, sigma)
    # y65 ~ normal(mu, sigma)
    # y66 ~ normal(mu, sigma)
    # y67 ~ normal(mu, sigma)
    # y68 ~ normal(mu, sigma)
    # y69 ~ normal(mu, sigma)
    # y70 ~ normal(mu, sigma)
    # y71 ~ normal(mu, sigma)
    # y72 ~ normal(mu, sigma)
    # y73 ~ normal(mu, sigma)
    # y74 ~ normal(mu, sigma)
    # y75 ~ normal(mu, sigma)
    # y76 ~ normal(mu, sigma)
    # y77 ~ normal(mu, sigma)
    # y78 ~ normal(mu, sigma)
    # y79 ~ normal(mu, sigma)
    # y80 ~ normal(mu, sigma)
    # y81 ~ normal(mu, sigma)
    # y82 ~ normal(mu, sigma)
    # y83 ~ normal(mu, sigma)
    # y84 ~ normal(mu, sigma)
    # y85 ~ normal(mu, sigma)
    # y86 ~ normal(mu, sigma)
    # y87 ~ normal(mu, sigma)
    # y88 ~ normal(mu, sigma)
    # y89 ~ normal(mu, sigma)
    # y90 ~ normal(mu, sigma)
    # y91 ~ normal(mu, sigma)
    # y92 ~ normal(mu, sigma)
    # y93 ~ normal(mu, sigma)
    # y94 ~ normal(mu, sigma)
    # y95 ~ normal(mu, sigma)
    # y96 ~ normal(mu, sigma)
    # y97 ~ normal(mu, sigma)
    # y98 ~ normal(mu, sigma)
    # y99 ~ normal(mu, sigma)
    # y100 ~ normal(mu, sigma)
end